//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistic
    {
        public int Id { get; set; }
        public string UserAgent { get; set; }
        public string Referrer { get; set; }
        public string HostIP { get; set; }
        public System.DateTime DateOfCreation { get; set; }
        public int RuleId { get; set; }
    
        public virtual Rule Rule { get; set; }
    }
}
